// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8E9WKY3TnX1tbc9ryJZDLVax-ccSAfvc',
    appId: '1:350764629575:web:a8f786bda4bbc2d1f5fb62',
    messagingSenderId: '350764629575',
    projectId: 'commerce-fe056',
    authDomain: 'commerce-fe056.firebaseapp.com',
    storageBucket: 'commerce-fe056.appspot.com',
    measurementId: 'G-8DTPH4LW6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32oauyyKk7l7I06JdcPicvfCx0vdCSFI',
    appId: '1:350764629575:android:36ce1c307b8b80baf5fb62',
    messagingSenderId: '350764629575',
    projectId: 'commerce-fe056',
    storageBucket: 'commerce-fe056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQ0hagav3YZ8tXIkQQwVRC7aM5A0QSFA',
    appId: '1:350764629575:ios:ade0c8e1893a5099f5fb62',
    messagingSenderId: '350764629575',
    projectId: 'commerce-fe056',
    storageBucket: 'commerce-fe056.appspot.com',
    iosBundleId: 'com.somethingprojectthataymade.eCommerceOfficialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQ0hagav3YZ8tXIkQQwVRC7aM5A0QSFA',
    appId: '1:350764629575:ios:3c6b7ff84435d79af5fb62',
    messagingSenderId: '350764629575',
    projectId: 'commerce-fe056',
    storageBucket: 'commerce-fe056.appspot.com',
    iosBundleId: 'com.somethingprojectthataymade.eCommerceOfficialApp.RunnerTests',
  );
}
